// Generated by uniFFI — do not edit manually
// MercyShieldPlus object for Rust calls

package com.mercyshieldplus

object MercyShieldPlus {
    init {
        System.loadLibrary("mercyshieldplus")
    }

    external fun generatePqKeypair(): Pair<String, String>

    external fun pqSignData(dsaSkB64: String, message: ByteArray): String

    external fun pqVerifyData(dsaPkB64: String, message: ByteArray, signatureB64: String): Boolean

    external fun pqSecureAttestationBlob(
        report: ByteArray,
        serverKemPkB64: String,
        localDsaSkB64: String? = null
    ): String
}
